# Configuration file for item-to-position layout optimization.

#-----------------------------------------------------------------------
# Paths
#-----------------------------------------------------------------------
paths:
  #item_pair_score_table:        "input/frequency/english-letter-pair-counts-google-ngrams_normalized.csv"
  item_pair_score_table:        "input/frequency/spanish-letter-pair-counts-leipzig_normalized.csv"
  position_pair_score_table:    "input/engram_2key_scores.csv"
  item_triple_score_table:      "" #"input/frequency/english-letter-triple-counts-google-ngrams_normalized.csv"
  position_triple_score_table:  "" #"input/engram_3key_order_scores.csv"
  layout_results_folder:        "output/layouts"

#-----------------------------------------------------------------------
# MOO (Multi-Objective Optimization) settings
#-----------------------------------------------------------------------
moo:
  default_objectives: 
    - "engram_key_preference"
    - "engram_row_separation"
    - "engram_same_row"
    - "engram_same_finger"
    #- "engram_order"
  default_weights: [1.0, 1.0, 1.0, 1.0] #, 1.0]
  default_maximize: [true, true, true, true] #, true]
  default_max_solutions: 10000
  default_time_limit: 100000
  show_progress_bar: true
  save_detailed_results: true

#-----------------------------------------------------------------------
# Optimization settings
#
# Example keyboard layout optimization problem:
#   Items:     etaoinsrhldcumfpgwybvkxjqz  # Spanish: eaonisrldctumpbgvqyhfjzxkw
#   Positions: FJDKEISLVMRUWOA;C,Z/QPX.'[
#-----------------------------------------------------------------------
#   _to_assign:    Items to arrange in available positions
#   _assigned:     Items already assigned to positions
#   _to_constrain: Subset of items_to_assign to arrange in positions_to_constrain,
#                  and subset of positions_to_assign to constrain items_to_constrain
optimization:   
  items_assigned:          ""
  items_to_assign:         "eaonisrldc"  # "etaoinsrhl"
  items_to_constrain:      "ea"          # "et"   
  positions_assigned:      ""
  positions_to_assign:     "ASDFJKL;EI"
  positions_to_constrain:  "DFJK"  

#-----------------------------------------------------------------------
# Visualization settings
#-----------------------------------------------------------------------
visualization: 
  print_keyboard: True
