# optimize_layouts/config.yaml
# Configuration file for item-to-position layout optimization.

#-----------------------------------------------------------------------
# Paths
#-----------------------------------------------------------------------
paths:
  input:
    raw_item_scores_file:          "input/letter_frequencies_english.csv"
    raw_item_pair_scores_file:     "input/letter_pair_frequencies_english.csv"
    raw_position_scores_file:      "input/key_comfort_estimates.csv"
    raw_position_pair_scores_file: "input/key_pair_comfort_estimates.csv"    
    item_scores_file:              "output/normalized_input/normalized_item_scores.csv"
    item_pair_scores_file:         "output/normalized_input/normalized_item_pair_scores.csv"
    position_scores_file:          "output/normalized_input/normalized_position_scores.csv"
    position_pair_scores_file:     "output/normalized_input/normalized_position_pair_scores.csv"
  output:
    layout_results_folder:         "output/layouts"

#-----------------------------------------------------------------------
# Optimization Settings
#-----------------------------------------------------------------------
# 24 letters/keys: etaoinsrhldcumfpgwybvkxj FDRSEVAWCQXZ JKULIM;O,P./
# Optimize arrangements of 16 by running in parallel with fixed letters:  
# 12 letters:        479,001,600 permutations (with 4 fixed letters)
# 13 letters:      6,227,020,800 permutations (with 3 fixed letters)
# 14 letters:     87,178,291,200 permutations (with 2 fixed letters)
# 16 letters: 20,922,789,888,000 permutations
optimization:   
  items_assigned:       "etaoi"         # Items already assigned to positions
  positions_assigned:   "FJRSE"         # Positions that are already filled 

  items_to_assign:      "nsrhldcumfpg"       # items to arrange in positions
  positions_to_assign:  "DVAWCKULIM;O"       # available positions

  # Subset of items_to_assign to arrange within positions_to_constrain, and
  # subset of positions_to_assign to constrain arrangement of items_to_constrain
  items_to_constrain:      ""   
  positions_to_constrain:  ""  

#-----------------------------------------------------------------------
# Visualization Settings
#-----------------------------------------------------------------------
visualization: 
  print_keyboard: True
