# optimize_layouts/config.yaml
# Configuration file for item-to-position layout optimization.

#-----------------------------------------------------------------------
# Paths
#-----------------------------------------------------------------------
paths:
  input:
    raw_item_scores_file:          "input/letter_frequencies_english.csv"
    raw_item_pair_scores_file:     "input/letter_pair_frequencies_english.csv"
    raw_position_scores_file:      "input/key_comfort_estimates.csv"
    raw_position_pair_scores_file: "input/key_pair_comfort_estimates.csv"    
    item_scores_file:              "output/normalized_input/normalized_item_scores.csv"
    item_pair_scores_file:         "output/normalized_input/normalized_item_pair_scores.csv"
    position_scores_file:          "output/normalized_input/normalized_position_scores.csv"
    position_pair_scores_file:     "output/normalized_input/normalized_position_pair_scores.csv"
  output:
    layout_results_folder:         "output/layouts"

#-----------------------------------------------------------------------
# Optimization Settings
#-----------------------------------------------------------------------
# Example with 24 items/positions: 
#    etaoinsrhldcumfpgwybvkxj FDESVRWACQZX JKILMUO;,P/.
# Optimize arrangements of 16 items by running fixed items in parallel:  
# 11 items:         79,833,600 permutations (with 5 fixed items)
# 12 items:        479,001,600 permutations (with 4 fixed items)
# 13 items:      6,227,020,800 permutations (with 3 fixed items)
# 14 items:     87,178,291,200 permutations (with 2 fixed items)
# 16 items: 20,922,789,888,000 permutations
optimization:   
  items_assigned:       "etao"         # Items already assigned to positions
  positions_assigned:   "MEUF" #"FJDE"         # Positions that are already filled 
  items_to_assign:      "insrhldcu"   # items to arrange in positions
  positions_to_assign:  "DSRVWAJKI" #"SVRWAKILMU"   # available positions

  # Subset of items_to_assign to arrange within positions_to_constrain, and
  # subset of positions_to_assign to constrain arrangement of items_to_constrain
  items_to_constrain:      ""   
  positions_to_constrain:  ""  

#-----------------------------------------------------------------------
# Visualization Settings
#-----------------------------------------------------------------------
visualization: 
  print_keyboard: True
