# optimize_layouts/config.yaml
# Configuration file for item-to-position layout optimization.

#-----------------------------------------------------------------------
# Paths
#-----------------------------------------------------------------------
paths:
  input:
    raw_item_scores_file:          "input/letter_frequencies_english.csv"
    raw_item_pair_scores_file:     "input/letter_pair_frequencies_english.csv"
    raw_position_scores_file:      "input/key_comfort_estimates.csv"
    raw_position_pair_scores_file: "input/key_pair_comfort_estimates.csv"    
    item_scores_file:              "output/normalized_input/normalized_item_scores.csv"
    item_pair_scores_file:         "output/normalized_input/normalized_item_pair_scores.csv"
    position_scores_file:          "output/normalized_input/normalized_position_scores.csv"
    position_pair_scores_file:     "output/normalized_input/normalized_position_pair_scores.csv"
  output:
    layout_results_folder:         "output/layouts"

#-----------------------------------------------------------------------
# Optimization Settings
#-----------------------------------------------------------------------
# Example for 13 of 24 items: etaoinsrhldcumfpgwybvkxj
# arranged in 13 of 24 positions: FDESVRWACQZXJKILMUO;,P/.
optimization:   
  items_assigned:       "etao"        # Items already assigned to positions
  positions_assigned:   "FJDE"        # Positions that are already filled 
  items_to_assign:      "insrhldcu"   # items to arrange in positions
  positions_to_assign:  "SVRWAKILMU"  # available positions

  # Subset of items_to_assign to arrange within positions_to_constrain, and
  # subset of positions_to_assign to constrain arrangement of items_to_constrain
  items_to_constrain:      ""   
  positions_to_constrain:  ""  

#-----------------------------------------------------------------------
# Visualization Settings
#-----------------------------------------------------------------------
visualization: 
  print_keyboard: True
