# Configuration file for item-to-position layout optimization.

#-----------------------------------------------------------------------
# Paths
#-----------------------------------------------------------------------
paths:
  item_pair_score_table:        "input/frequency/english-letter-pair-counts-google-ngrams_normalized.csv"
  item_triple_score_table:      "input/frequency/english-letter-triple-counts-google-ngrams_normalized.csv"
  position_pair_score_table:    "input/engram_2key_scores.csv"
  position_triple_score_table:  None  # "input/engram_3key_order_scores.csv"
  layout_results_folder:        "output/layouts"

#-----------------------------------------------------------------------
# MOO (Multi-Objective Optimization) settings
#-----------------------------------------------------------------------
moo:
  default_objectives: 
    - "engram_keys"
    - "engram_rows"
    - "engram_columns"
    - "engram_order"
  default_weights: [1.0, 1.0, 1.0, 1.0]
  default_maximize: [true, true, true, true]
  default_max_solutions: 10000
  default_time_limit: 100000
  show_progress_bar: true
  save_detailed_results: true

#-----------------------------------------------------------------------
# Optimization settings
#
# Example keyboard optimization problem:
#   Items (letters by frequency):  etaoin srhldc umfpgw ybvkxj
#   Positions (keys by comfort):   JFKDIE LSMVUR ;AOW,C /ZPQ.X
#-----------------------------------------------------------------------
#   _to_assign:    Items to arrange in available positions
#   _assigned:     Items already assigned to positions
#   _to_constrain: Subset of items_to_assign to arrange in positions_to_constrain,
#                  and subset of positions_to_assign to constrain items_to_constrain
optimization:   
  items_to_assign:         "etaoinsrhl"
  positions_to_assign:     "JFKDIELSMV"
  items_assigned:          ""   
  positions_assigned:      ""  
  items_to_constrain:      ""   
  positions_to_constrain:  ""  

#-----------------------------------------------------------------------
# Visualization settings
#-----------------------------------------------------------------------
visualization: 
  print_keyboard: True
