# optimize_layouts/config.yaml
# Configuration file for item-to-position layout optimization.

#-----------------------------------------------------------------------
# Paths (raw input files can be anywhere)
#-----------------------------------------------------------------------
paths:
  input:
    raw_item_scores_file:          "input/frequency/english-letter-counts-leipzig.csv"
    raw_item_pair_scores_file:     "input/frequency/english-letter-pair-counts-leipzig.csv"
    raw_position_scores_file:      "input/comfort/key-comfort-scores.csv"
    raw_position_pair_scores_file: "input/comfort/key-pair-comfort-scores.csv"
  output:
    layout_results_folder:         "output/layouts"

#-----------------------------------------------------------------------
# Optimization settings
#-----------------------------------------------------------------------
# Example for 12 of 24 items: etaoinsrhldc umfpgwybvkxj
# arranged in 12 of 24 positions: FDESVRJKILMU WACQZXO;,P/.
optimization:   
  items_assigned:       ""      # Items already assigned to positions
  positions_assigned:   ""      # Positions that are already filled 
  items_to_assign:      "etaoinsrhldc" # items to arrange in positions
  positions_to_assign:  "FDESVRJKILMU" # available positions

  # Subset of items_to_assign to arrange within positions_to_constrain
  # and subset of positions_to_assign to constrain items_to_constrain
  items_to_constrain:      ""   
  positions_to_constrain:  ""  

#-----------------------------------------------------------------------
# Visualization settings
#-----------------------------------------------------------------------
visualization: 
  print_keyboard: False
