# Configuration file for item-to-position layout optimization.

#-----------------------------------------------------------------------
# Paths
#-----------------------------------------------------------------------
paths:
  item_pair_score_table:        "input/frequency/english-letter-pair-counts-google-ngrams_normalized.csv"
  item_triple_score_table:      "input/frequency/english-letter-triple-counts-google-ngrams_normalized.csv"
  position_pair_score_table:    "input/engram_2key_scores.csv"
  position_triple_score_table:  None  # "input/engram_3key_order_scores.csv"
  layout_results_folder:        "output/layouts"

#-----------------------------------------------------------------------
# MOO (Multi-Objective Optimization) settings
#-----------------------------------------------------------------------
moo:
  default_objectives: 
    - "engram_key_preference"
    - "engram_avg4_score"  # engram_[row_separation, same_row, same_finger, outside]
    #- "engram_row_separation"
    #- "engram_same_row"
    #- "engram_same_finger"
    #- "engram_outside"  # Irrelevant to this optimization code
  default_weights: [1.0, 1.0] #, 1.0, 1.0]
  default_maximize: [true, true] #, true, true]
  default_max_solutions: 10000
  default_time_limit: 100000
  show_progress_bar: true
  save_detailed_results: true

#-----------------------------------------------------------------------
# Optimization settings
#
# Example keyboard layout optimization problem:
#   Items (letters by frequency):     etaoi nsrh ldcu mfpgwybvkxj
#   Positions (keys by preference):   FJDKEISL VMRU WOA;C, Z/QPX.
#   Strategy: For every possible arrangement of 5 letters in 8 keys,
#     arrange the next most-frequent 8 letters in the top 18 keys.
#     Then for each of these, arrange the next 11 letters.
#-----------------------------------------------------------------------
#   _to_assign:    Items to arrange in available positions
#   _assigned:     Items already assigned to positions
#   _to_constrain: Subset of items_to_assign to arrange in positions_to_constrain,
#                  and subset of positions_to_assign to constrain items_to_constrain
optimization:   
  items_to_assign:         "nsrhldcu"
  positions_to_assign:     "ISLVMRUWOA;C,"
  items_assigned:          "etaoi"
  positions_assigned:      "JFDKE"  
  items_to_constrain:      "nsrh"
  positions_to_constrain:  "ISLVMRUWOA;"

#-----------------------------------------------------------------------
# Visualization settings
#-----------------------------------------------------------------------
visualization: 
  print_keyboard: True
