# Configuration file for item-to-position layout optimization.

#-----------------------------------------------------------------------
# Paths
#-----------------------------------------------------------------------
paths:
  item_pair_score_table:        "input/frequency/english-letter-pair-counts-google-ngrams_normalized.csv"
  position_pair_score_table:    "input/engram_2key_scores.csv"
  item_triple_score_table:      "input/frequency/english-letter-triple-counts-google-ngrams_normalized.csv"
  position_triple_score_table:  "input/engram_3key_order_scores.csv"
  layout_results_folder:        "output/layouts"

#-----------------------------------------------------------------------
# MOO (Multi-Objective Optimization) settings
#-----------------------------------------------------------------------
moo:
  default_objectives: 
    - "engram_key_preference"
    - "engram_row_separation"
    - "engram_same_row"
    - "engram_same_finger"
    - "engram_order"
  default_weights: [1.0, 1.0, 1.0, 1.0, 1.0]
  default_maximize: [true, true, true, true, true]
  default_max_solutions: 10000
  default_time_limit: 100000
  show_progress_bar: true
  save_detailed_results: true

#-----------------------------------------------------------------------
# Optimization settings
#
# Example keyboard layout optimization problem:
#   Items (letters by frequency):     etaoi nsrh ldcu mfpgwybvkxj
#   Positions (keys by preference):   FJDKEISLVMRUWOA; C,Z/QPX.
#   Strategy: For every possible arrangement of top 4 letters in 8 keys,
#     arrange the next most-frequent 9 letters in the top 16 keys.
#     Then for each of these, arrange the next 11 letters.
#-----------------------------------------------------------------------
#   _to_assign:    Items to arrange in available positions
#   _assigned:     Items already assigned to positions
#   _to_constrain: Subset of items_to_assign to arrange in positions_to_constrain,
#                  and subset of positions_to_assign to constrain items_to_constrain
#optimization:   
#  items_to_assign:         "insrhldcu"
#  positions_to_assign:     "EISLVMRUWOA;"
#  items_assigned:          "etao"
#  positions_assigned:      "JFDK"  
#  items_to_constrain:      "insr"
#  positions_to_constrain:  "EISLVMRUWO"
#optimization:   
#  items_assigned:       "etaoinsrhldcu"
#  positions_assigned:   "ILSKEMJFRVDAU"
#  items_to_assign:      "mfpgwybvkxj"
#  positions_to_assign:  "WO;C,Z/QPX."
#  items_to_constrain:      "xj"   
#  positions_to_constrain:  "Z/QPX."  
optimization:   
  items_assigned:       ""
  positions_assigned:   ""
  items_to_assign:      "etaoinsrhl"
  positions_to_assign:  "ASDFJKL;EI"
  items_to_constrain:      "et"   
  positions_to_constrain:  "DFJK"  

#-----------------------------------------------------------------------
# Visualization settings
#-----------------------------------------------------------------------
visualization: 
  print_keyboard: True
